name: Ping Vercel Cron Endpoints

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (minimum GH Actions interval)
  workflow_dispatch:        # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Stocks ingest
        run: |
          curl -fsS "https://chatter-gpt-ten.vercel.app/api/cron/reddit?domain=stocks" || true
      - name: Crypto ingest
        run: |
          curl -fsS "https://chatter-gpt-ten.vercel.app/api/cron/reddit?domain=crypto" || true
      - name: SEC latest (optional stub)
        run: |
          curl -fsS "https://chatter-gpt-ten.vercel.app/api/cron/sec-latest" || true
